import { useState } from "react";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import Darkmode from "../components/darkmode";

import css from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const [darkmode, setdarkmode] = useState(true);

	const switchDarkmode = function () {
		if (darkmode === true) {
			setdarkmode(false);
		} else {
			setdarkmode(true);
		}
	};

	return (
		<>
			<Head>
				<title>TODO App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Darkmode estado={darkmode}>
				<section>
					<header className={css.header}>
						<h1>TODO</h1>
						<button onClick={switchDarkmode} type="button">
							{darkmode ? (<img src="assets/svg/sun.svg" alt="solcito" />) : (<img src="assets/svg/moon.svg" alt="lalunallena" />)}
						</button>
					</header>
					<section className="crear">
						<h3>CREAR</h3>
						<section className="todos">
							<ul>
								<li>tarea 1</li>
								<li>tarea 2</li>
								<li>tarea 3</li>
								<li>tarea 4</li>
							</ul>
						</section>
					</section>
				</section>
			</Darkmode>
		</>
	);
}
