import { useState, useEffect } from "react";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import Darkmode from "../components/darkmode";

import header from "../styles/Header.module.css";
import crear from "../styles/Crear.module.css";
import todos from "../styles/Todos.module.css";
import css from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

function Header(props) {
	const { estado, elon } = props;

	return (
		<header className={header.header}>
			<h1>TODO</h1>
			<button onClick={elon} type="button">
				{
					estado
						? (<img src="assets/svg/sun.svg" alt="solcito" />)
						: (<img src="assets/svg/moon.svg" alt="lalunallena" />)
				}
			</button>
		</header>
	);
}

function Crear() {
	const agregaDB = function () {
		const valor = document.querySelector(".addTODO").value;
		if (valor.length === 0) {
			console.debug( "No hay un TODO por agregar" );
		} else {
			console.debug( `Valor: ${valor}` );
		}
	};

	return (
		<section className={crear.crear}>
			<ul>
				<li>
					<input className="addTODO" type="text" placeholder="Create a new todo ..." />
					<button onClick={agregaDB} type="button">+</button>
				</li>
			</ul>
		</section>
	);
}

function Todos() {
	return (
		<section className={todos.todos}>
			<ul>
				<li>tarea 1</li>
				<li>tarea 2</li>
				<li>tarea 3</li>
				<li>tarea 4</li>
			</ul>
		</section>
	);
}

function NavInferior() {
	return (
		<nav className={NavInferior.menu}>
			<p>5 items left</p>
			<ul>
				<li>all</li>
				<li>active</li>
				<li>completed</li>
			</ul>
			<p>Clear Completed</p>
		</nav>
	);
}

export default function Home() {
	const [darkmode, setdarkmode] = useState();

	const estadoDarkmode = function () {
		if ( localStorage.getItem("todoapp_darkmode") === null ) {
			localStorage.setItem("todoapp_darkmode", false);
		} else if ( localStorage.getItem("todoapp_darkmode") === "false" ) {
			setdarkmode(false);
		} else {
			setdarkmode(true);
		}
	};
	const switchDarkmode = function () {
		if (darkmode === true) {
			setdarkmode(false);
			localStorage.setItem("todoapp_darkmode", false);
		} else {
			setdarkmode(true);
			localStorage.setItem("todoapp_darkmode", true);
		}
	};

	useEffect(() => {
		estadoDarkmode();
	}, []);

	return (
		<>
			<Head>
				<title>TODO App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Darkmode estado={darkmode}>
				<span className={css.imagenheader} />
				<section>
					<Header estado={darkmode} elon={() => { switchDarkmode(); }} />
					<Crear />
					<Todos />
					<NavInferior />
				</section>
			</Darkmode>
		</>
	);
}
