import { useState } from "react";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import Darkmode from "../components/darkmode";

import css from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const [darkmode, setdarkmode] = useState(true);

	const switchDarkmode = function () {
		if (darkmode === true) {
			setdarkmode(false);
		} else {
			setdarkmode(true);
		}
	};

	const cssboton = {
		background: "red",
		border: "none",
		fontSize: "2em",
		color: "white",
		margin: "0 auto",
		width: "200px",
		display: "block",
	};

	return (
		<>
			<Head>
				<title>TODO App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Darkmode estado={darkmode}>
				<header className={css.header}>
					<h1>TODO</h1>
					<button onClick={switchDarkmode} style={cssboton} type="button">
						{darkmode ? (<img src="assets/svg/sun.svg" alt="solcito" />) : (<img src="assets/svg/moon.svg" alt="lalunallena" />)}
					</button>
				</header>
			</Darkmode>
		</>
	);
}
